import { useCallback, useMemo, useRef, useState } from 'react';
import { parseXMLSteps } from '../../utils/xmlParser';
import { buildTestCaseData } from '../../utils/testCaseBuilder';
import { applyAutoGeneratedDescription } from '../../utils/stepSmartDefaults';
import { ACTION_REGISTRY } from '../../utils/actionRegistry';
import { updateTestCase, fetchTestCaseDetail } from '../../services/adoApi';
import type { ParsedStep } from './StepsEditor';
import type { ADOTestCase } from '../../types';
import type { WorkspaceSettingsValues } from '../pages/WorkspaceSettings';

export interface TestCaseEditorFormData {
  title: string;
  status: string;
  method: string;
  region: string;
  execProcess: string;
  pltpProcess: string;
  initialSteps: string;
}

const EMPTY_FORM: TestCaseEditorFormData = {
  title: '',
  status: '',
  method: '',
  region: '',
  execProcess: '',
  pltpProcess: '',
  initialSteps: '',
};

function fieldText(value: unknown): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    const candidate = obj.displayName ?? obj.uniqueName ?? obj.value ?? obj.name;
    if (typeof candidate === 'string') return candidate;
    try {
      return JSON.stringify(value);
    } catch {
      return '';
    }
  }
  return '';
}

function buildFormFromCase(testCase: ADOTestCase): TestCaseEditorFormData {
  const fields = testCase.fields ?? {};
  return {
    title: testCase.name || fieldText(fields['System.Title']),
    status: testCase.state || fieldText(fields['System.State']),
    method: fieldText(fields['Custom.TestingMethod']).trim(),
    region: fieldText(fields['Custom.ApplicableRegions']).trim(),
    execProcess: fieldText(fields['Custom.ExecutiveProcess']).trim(),
    pltpProcess: fieldText(fields['Custom.PLTPProcessArea']).trim(),
    initialSteps: fieldText(fields['Custom.InitialStep']),
  };
}

function buildStepsFromCase(testCase: ADOTestCase): ParsedStep[] {
  const raw = fieldText(testCase.fields?.['Microsoft.VSTS.TCM.Steps']).trim();
  if (!raw) return [];
  const { steps } = parseXMLSteps(raw);
  return steps.map((step, idx) => applyAutoGeneratedDescription({ ...step, index: idx + 1 }));
}

function normalizeStepForCompare(step: ParsedStep) {
  const rest = { ...step } as ParsedStep & { index?: number };
  delete rest.index;
  return rest;
}

export function validateTestCaseEditor(
  formData: TestCaseEditorFormData,
  steps: ParsedStep[],
): string[] {
  const errors: string[] = [];
  if (!formData.title.trim()) errors.push('Test Title is required');
  if (!formData.status.trim()) errors.push('Status is required');
  if (!formData.method.trim()) errors.push('Testing Method is required');
  if (!formData.region.trim()) errors.push('Region is required');
  if (!formData.execProcess.trim()) errors.push('Executive Process is required');
  if (!formData.pltpProcess.trim()) errors.push('PLTP Process is required');
  if (steps.length === 0) errors.push('At least one step is required');

  steps.forEach((step, idx) => {
    if (!step.action.trim()) {
      errors.push(`Step ${idx + 1}: Action is required`);
      return;
    }
    const actionDef = ACTION_REGISTRY[step.action];
    if (actionDef?.contract.locator === 'required' && !step.element?.trim()) {
      errors.push(`Step ${idx + 1}: Locator is required`);
    }
    if (!step.description?.trim()) {
      errors.push(`Step ${idx + 1}: Step Description is required`);
    }
  });

  return errors;
}

export interface UseTestCaseEditorOptions {
  workspaceSettings: WorkspaceSettingsValues;
  /** Called after a successful save with the reloaded test case. */
  onSaved?: (updated: ADOTestCase) => void;
  /**
   * Optional post-save hook (e.g. local SQLite re-sync). Errors are caught
   * and returned via the save result's `syncError` rather than thrown.
   */
  postSaveSync?: (updated: ADOTestCase) => Promise<void> | void;
}

export interface SaveResult {
  ok: boolean;
  updatedCase?: ADOTestCase;
  error?: string;
  syncError?: string;
}

/**
 * Canonical test-case edit state + validation + save pipeline, shared by the
 * test-case detail page and the shared-step editor modal so there is exactly
 * one implementation of the edit/save behavior.
 */
export function useTestCaseEditor({
  workspaceSettings,
  onSaved,
  postSaveSync,
}: UseTestCaseEditorOptions) {
  const [formData, setFormData] = useState<TestCaseEditorFormData>(EMPTY_FORM);
  const [steps, setSteps] = useState<ParsedStep[]>([]);
  const [validationErrors, setValidationErrors] = useState<string[]>([]);
  const [isSaving, setIsSaving] = useState(false);
  const baselineRef = useRef<{ formData: TestCaseEditorFormData; steps: ParsedStep[] } | null>(null);
  const caseRef = useRef<ADOTestCase | null>(null);
  const reloadControllerRef = useRef<AbortController | null>(null);

  /** Snapshot the editor from a test case (call when entering edit mode). */
  const beginEdit = useCallback((testCase: ADOTestCase) => {
    const nextForm = buildFormFromCase(testCase);
    const nextSteps = buildStepsFromCase(testCase);
    caseRef.current = testCase;
    baselineRef.current = { formData: nextForm, steps: nextSteps };
    setFormData(nextForm);
    setSteps(nextSteps);
    setValidationErrors([]);
  }, []);

  const resetToBaseline = useCallback(() => {
    const baseline = baselineRef.current;
    if (!baseline) return;
    setFormData(baseline.formData);
    setSteps(baseline.steps);
    setValidationErrors([]);
  }, []);

  const isDirty = useMemo(() => {
    const baseline = baselineRef.current;
    if (!baseline) return false;
    return (
      JSON.stringify(formData) !== JSON.stringify(baseline.formData)
      || JSON.stringify(steps.map(normalizeStepForCompare))
        !== JSON.stringify(baseline.steps.map(normalizeStepForCompare))
    );
  }, [formData, steps]);

  const save = useCallback(async (): Promise<SaveResult> => {
    const testCase = caseRef.current;
    if (!testCase || isSaving) return { ok: false, error: 'Editor not ready.' };

    const errors = validateTestCaseEditor(formData, steps);
    if (errors.length > 0) {
      setValidationErrors(errors);
      return { ok: false, error: errors[0] };
    }

    setIsSaving(true);
    let reloadController: AbortController | null = null;
    try {
      const testCaseData = buildTestCaseData(formData, steps);
      const href = testCase._links?.workItem?.href ?? testCase._links?.self?.href;
      await updateTestCase(workspaceSettings, testCase.id, testCaseData, href);

      reloadControllerRef.current?.abort();
      reloadController = new AbortController();
      reloadControllerRef.current = reloadController;
      const updatedCase = await fetchTestCaseDetail(
        workspaceSettings,
        testCase.id,
        href,
        undefined,
        reloadController.signal,
      );

      const editedTitle = formData.title || fieldText(updatedCase.fields?.['System.Title']);
      const nextUpdatedCase = editedTitle
        ? {
            ...updatedCase,
            name: editedTitle,
            fields: { ...updatedCase.fields, 'System.Title': editedTitle },
          }
        : updatedCase;

      caseRef.current = nextUpdatedCase;
      baselineRef.current = {
        formData: buildFormFromCase(nextUpdatedCase),
        steps: buildStepsFromCase(nextUpdatedCase),
      };
      setValidationErrors([]);

      let syncError: string | undefined;
      if (postSaveSync) {
        try {
          await postSaveSync(updatedCase);
        } catch (err) {
          syncError = err instanceof Error ? err.message : 'Local DB sync failed.';
        }
      }

      onSaved?.(nextUpdatedCase);
      if (reloadControllerRef.current === reloadController) {
        reloadControllerRef.current = null;
      }
      return { ok: true, updatedCase: nextUpdatedCase, syncError };
    } catch (error) {
      if (reloadController?.signal.aborted) {
        return { ok: false, error: 'Save reload aborted.' };
      }
      const message = error instanceof Error ? error.message : 'Failed to save changes';
      setValidationErrors([`Save failed: ${message}`]);
      return { ok: false, error: message };
    } finally {
      if (!reloadController?.signal.aborted) {
        setIsSaving(false);
      }
    }
  }, [formData, steps, isSaving, workspaceSettings, onSaved, postSaveSync]);

  return {
    formData,
    setFormData,
    steps,
    setSteps,
    validationErrors,
    setValidationErrors,
    isSaving,
    isDirty,
    beginEdit,
    resetToBaseline,
    save,
  };
}
