import React, {useCallback, useEffect, useMemo, useRef, useState} from 'react';
import {MainLayout} from '../layouts/MainLayout';
import {PageDetailLayout} from '../layouts/PageDetailLayout';
import {IconAttachFile, IconCopy, IconOpenInNew, IconFolderCode, IconSearch, IconX} from '../Common/Icons';
import type {ADOTestCase, ADOTestPlan, ADOTestSuite} from '../../types';
import type {WorkspaceSettingsValues} from './WorkspaceSettings';
import {buildWorkItemAdoUrl, fetchTestCaseDetail, updateTestCase} from '../../services/adoApi';
import {parseXMLSteps} from '../../utils/xmlParser';
import {buildTestCaseData} from '../../utils/testCaseBuilder';
import type {ParsedStep} from '../TestCases/StepsEditor';
import {StepsEditor, StepsSearchBar, useStepsSearch} from '../TestCases/StepsEditor';
import {SharedStepPreviewModal} from '../TestCases/SharedStepPreviewModal';
import {SeleniumRepoBrowserModal} from '../TestCases/SeleniumRepoBrowserModal';
import {TestCaseFormFields} from '../TestCases/TestCaseFormFields';
import {ACTION_REGISTRY} from '../../utils/actionRegistry';
import {useNotification} from '../../context/useNotification';
import azureLogo from '../../assets/azure.png';
import { applyAutoGeneratedDescription } from '../../utils/stepSmartDefaults';
import { buildCloneDraftFromTestCase, type CloneSourceMeta, type CreateTestCaseDraft } from '../../utils/testCaseClone';
import {
  buildAutomatedMethodCode,
  buildAutomatedMethodName,
  buildAutomatedTestFullName,
  ensureMethodDoesNotExist,
  getClassNameFromFilePath,
  insertAutomatedTestMethod,
  parseAutomatedTestFullName,
} from '../../utils/automatedTestGenerator';

interface TestCaseDetailProps {
  plan: ADOTestPlan;
  suite: ADOTestSuite;
  caseId: number;
  caseData?: ADOTestCase;
  workspaceSettings: WorkspaceSettingsValues;
  onBackToCases: () => void;
  onClone?: (draft: CreateTestCaseDraft, sourceMeta: CloneSourceMeta) => void;
  onTitleChange?: (title: string) => void;
  onCaseUpdated?: (testCase: ADOTestCase) => void;
  onHelpClick?: () => void;
  onSettingsClick: () => void;
  embedded?: boolean;
}

interface StepViewModel {
  index: number;
  name: string;
  fullText: string;
}

interface DetailRow {
  label: string;
  value: string;
}

interface TestRunLogEntry {
  id: string;
  level: 'info' | 'error';
  message: string;
  timestamp: string;
}

type TestExecutionMode = 'run' | 'debug';
type DetailMenuType = 'more-details' | 'action' | 'local-execution' | null;
const DEBUGGER_UI_ENABLED = false;
const LOCAL_EXECUTION_LOG_CACHE_PREFIX = 'bcm-testbuilder:last-local-execution-log:v1';

interface CachedLocalExecutionLog {
  runMode: TestExecutionMode;
  runStatus: 'idle' | 'running' | 'complete' | 'failed' | 'cancelled';
  logEntries: Array<{
    level: 'info' | 'error';
    message: string;
    timestamp: string;
  }>;
  attachments: string[];
  savedAt: string;
}

function buildLocalExecutionLogCacheKey(caseId: number): string {
  return `${LOCAL_EXECUTION_LOG_CACHE_PREFIX}:${caseId}`;
}

function readCachedLocalExecutionLog(caseId: number): CachedLocalExecutionLog | null {
  try {
    const raw = window.localStorage.getItem(buildLocalExecutionLogCacheKey(caseId));
    if (!raw) return null;
    const parsed = JSON.parse(raw) as CachedLocalExecutionLog;
    if (!parsed || !Array.isArray(parsed.logEntries) || !Array.isArray(parsed.attachments)) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}

function writeCachedLocalExecutionLog(caseId: number, payload: CachedLocalExecutionLog): void {
  try {
    window.localStorage.setItem(buildLocalExecutionLogCacheKey(caseId), JSON.stringify(payload));
  } catch {
    // Ignore cache write failures (quota/private mode).
  }
}


function mergeTestCaseData(primary: ADOTestCase, fallback?: ADOTestCase | null): ADOTestCase {
  if (!fallback) return primary;

  return {
    ...fallback,
    ...primary,
    testPlanName: primary.testPlanName ?? fallback.testPlanName,
    testSuiteName: primary.testSuiteName ?? fallback.testSuiteName,
    configurationName: primary.configurationName ?? fallback.configurationName,
    automationStatus: primary.automationStatus ?? fallback.automationStatus,
    assignedTo: primary.assignedTo ?? fallback.assignedTo,
    tester: primary.tester ?? fallback.tester,
    lastUpdatedBy: primary.lastUpdatedBy ?? fallback.lastUpdatedBy,
    fields: {
      ...fallback.fields,
      ...primary.fields,
    },
    _links: {
      ...(fallback._links ?? {}),
      ...(primary._links ?? {}),
    },
  };
}

function normalizeFieldText(value: unknown): string {
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return '';
}

function hasAutomationFieldValue(value: string): boolean {
  const normalized = value.trim().toLowerCase();
  return normalized.length > 0 && normalized !== 'not set';
}

function guidFromBytes(bytes: Uint8Array): string {
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0'));
  return `${hex[3]}${hex[2]}${hex[1]}${hex[0]}-${hex[5]}${hex[4]}-${hex[7]}${hex[6]}-${hex[8]}${hex[9]}-${hex[10]}${hex[11]}${hex[12]}${hex[13]}${hex[14]}${hex[15]}`;
}

async function createAutomationGuid(fullyQualifiedTestName: string): Promise<string> {
  const input = fullyQualifiedTestName || '';
  const utf16le = new Uint8Array(input.length * 2);
  for (let i = 0; i < input.length; i += 1) {
    const code = input.charCodeAt(i);
    utf16le[i * 2] = code & 0xff;
    utf16le[i * 2 + 1] = (code >> 8) & 0xff;
  }
  const digest = await crypto.subtle.digest('SHA-1', utf16le);
  const hash = new Uint8Array(digest);
  return guidFromBytes(hash.slice(0, 16));
}

function decodeHtmlEntities(input: string): string {
  return input
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, '\'')
    .replace(/&nbsp;/g, ' ');
}

function isScreenshotAttachment(filePath: string): boolean {
  return /\.(png|jpe?g|gif|bmp|webp|avif)$/i.test(filePath);
}

function extractDebugBreakpointsFromLogs(entries: TestRunLogEntry[]): Array<{ sourcePath: string; line: number }> {
  const breakpoints: Array<{ sourcePath: string; line: number }> = [];
  const seen = new Set<string>();
  const stackTracePattern = /([A-Za-z]:\\[^:\r\n]+\.cs):line\s+(\d+)/i;

  for (const entry of entries) {
    const message = String(entry?.message || '');
    const match = message.match(stackTracePattern);
    if (!match) continue;
    const sourcePath = match[1].trim();
    const line = Number(match[2]);
    if (!sourcePath || !Number.isInteger(line) || line <= 0) continue;

    const key = `${sourcePath.toLowerCase()}::${line}`;
    if (seen.has(key)) continue;
    seen.add(key);
    breakpoints.push({ sourcePath, line });
  }

  return breakpoints;
}

function stripLegacyTcPrefix(methodName: string): string {
  return methodName.replace(/^TC\d+[_\-\s]*/i, '').trim();
}

function parseExactStepQuery(query: string): number | null {
  const match = query.trim().match(/^(?:step\s*)?#?\s*(\d+)$/i);
  if (!match) return null;
  const stepNumber = Number(match[1]);
  return Number.isInteger(stepNumber) && stepNumber >= 0 ? stepNumber : null;
}

function parseStepLines(rawSteps: unknown): string[] {
  const input = normalizeFieldText(rawSteps).trim();
  if (!input) return [];

  const decoded = decodeHtmlEntities(input);
  const withLineBreaks = decoded
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/(p|div|li|step|parameterizedstring|formattedtext|description|expected|action)>/gi, '\n');
  const withoutTags = withLineBreaks.replace(/<[^>]+>/g, ' ');
  return withoutTags
    .split(/\r?\n/)
    .map((line) => line.replace(/\s+/g, ' ').trim())
    .filter(Boolean);
}

function formatActionName(action: string): string {
  return action
    .toLowerCase()
    .split('_')
    .filter(Boolean)
    .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
    .join(' ');
}

function extractActionFromLine(line: string): string | null {
  const match = line.match(/(?:^|\|)\s*Action=([^|]+)/i);
  if (!match || !match[1]) return null;
  const action = match[1].trim();
  return action.length > 0 ? action : null;
}

function formatStepTextWithBoldLabels(text: string): React.ReactNode[] {
  const parts: React.ReactNode[] = [];
  const segments = text.split(/(\|)/);

  segments.forEach((segment, index) => {
    if (segment === '|') {
      parts.push('|');
    } else if (segment.trim()) {
      const match = segment.match(/^(\s*)([^=]+)(=.*)$/);
      if (match) {
        const [, leading, label, rest] = match;
        if (leading) parts.push(leading);
        parts.push(<strong key={`label-${index}`}>{label.trim()}</strong>);
        parts.push(rest);
      } else {
        parts.push(segment);
      }
    }
  });

  return parts;
}

function extractDescriptionFromLine(line: string): string | null {
  const match = line.match(/(?:^|\|)\s*Description=([^|]+)/i);
  if (!match || !match[1]) return null;
  const description = match[1].trim();
  return description.length > 0 ? description : null;
}

function buildFullTextFromParsedStep(step: {
  action: string;
  element?: string;
  elementCategory?: string;
  value?: string;
  expectedValue?: string;
  key?: string;
  headers?: string;
  description?: string;
}): string {
  const parts = [
    ['Action', step.action],
    ['Element', step.element],
    ['ElementCategory', step.elementCategory],
    ['Description', step.description],
    ['Value', step.value],
    ['ExpectedVl', step.expectedValue],
    ['DataKey', step.key],
    ['Headers', step.headers],
  ]
    .filter(([, value]) => Boolean(value && value.trim().length > 0))
    .map(([label, value]) => `${label}=${value}`);

  return parts.join('|');
}

function parseStepsForDisplay(rawSteps: unknown): StepViewModel[] {
  const input = normalizeFieldText(rawSteps).trim();
  if (!input) return [];

  const lines = parseStepLines(rawSteps);
  const actionLines = lines.filter((line) => /(?:^|\|)\s*Action=/i.test(line));
  const parsed = parseXMLSteps(input).steps;

  if (parsed.length > 0) {
    return parsed.map((step, index) => {
      const fallbackLine = actionLines[index] || lines[index] || buildFullTextFromParsedStep(step);
      const description = step.description?.trim() || extractDescriptionFromLine(fallbackLine);
      const actionName = formatActionName(step.action || extractActionFromLine(fallbackLine) || 'Step');
      return {
        index: index + 1,
        name: description || actionName || `Step ${index + 1}`,
        fullText: fallbackLine || buildFullTextFromParsedStep(step),
      };
    });
  }

  const sourceLines = actionLines.length > 0 ? actionLines : lines;
  return sourceLines.map((line, index) => {
    const description = extractDescriptionFromLine(line);
    const action = extractActionFromLine(line);
    return {
      index: index + 1,
      name: description || formatActionName(action || 'Step'),
      fullText: line,
    };
  });
}

function formatDateTime(value: unknown): string {
  const raw = normalizeFieldText(value).trim();
  if (!raw) return '';
  const parsed = new Date(raw);
  if (Number.isNaN(parsed.getTime())) return raw;
  const day = String(parsed.getDate()).padStart(2, '0');
  const month = String(parsed.getMonth() + 1).padStart(2, '0');
  const year = String(parsed.getFullYear());
  const hours = String(parsed.getHours()).padStart(2, '0');
  const minutes = String(parsed.getMinutes()).padStart(2, '0');
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

function toIdentityDisplay(value: unknown): string {
  if (!value) return '';
  if (typeof value === 'string') return value.trim();
  if (typeof value === 'object') {
    const identity = value as { displayName?: unknown; uniqueName?: unknown };
    const displayName = normalizeFieldText(identity.displayName).trim();
    const uniqueName = normalizeFieldText(identity.uniqueName).trim();
    if (displayName && uniqueName && displayName !== uniqueName) return `${displayName} (${uniqueName})`;
    return displayName || uniqueName;
  }
  return '';
}

function toDisplayValue(value: unknown): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'string') return value.trim();
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (typeof value === 'object') {
    const identity = toIdentityDisplay(value);
    if (identity) return identity;
    try {
      return JSON.stringify(value);
    } catch {
      return '';
    }
  }
  return '';
}


function buildMainDetailRows(testCase: ADOTestCase): DetailRow[] {
  const fields = testCase.fields ?? {};
  const testingMethod = toDisplayValue(fields['Custom.TestingMethod']) || 'Not set';
  const region = toDisplayValue(fields['Custom.ApplicableRegions']) || 'Not set';
  const execProcess = toDisplayValue(fields['Custom.ExecutiveProcess']) || 'Not set';
  const pltpProcess = toDisplayValue(fields['Custom.PLTPProcessArea']) || 'Not set';
  const assignedLabel = testCase.assignedTo?.displayName || toIdentityDisplay(fields['System.AssignedTo']) || 'Unassigned';

  return [
    {label: 'Status', value: testCase.state},
    {label: 'Testing Method', value: testingMethod},
    {label: 'Region', value: region},
    {label: 'Executive Process', value: execProcess},
    {label: 'PLTP Process', value: pltpProcess},
    {label: 'Assigned To', value: assignedLabel},
  ];
}

function buildAdditionalDetailRows(testCase: ADOTestCase, plan: ADOTestPlan): DetailRow[] {
  const fields = testCase.fields ?? {};
  const automationStatus = testCase.automationStatus || toDisplayValue(fields['Microsoft.VSTS.TCM.AutomationStatus']) || 'Unknown';
  const configuration = testCase.configurationName || 'Default configuration';

  return [
    {label: 'Configuration', value: configuration},
    {label: 'Automation', value: automationStatus},
    {label: 'Priority', value: String(testCase.priority)},
    {label: 'Iteration Path', value: toDisplayValue(fields['System.IterationPath']) || plan.iteration},
    {label: 'Area Path', value: toDisplayValue(fields['System.AreaPath']) || plan.areaPath},
    {label: 'Tester', value: testCase.tester?.displayName || ''},
    {label: 'Automated Test Name', value: toDisplayValue(fields['Microsoft.VSTS.TCM.AutomatedTestName'])},
    {label: 'Automated Test Storage', value: toDisplayValue(fields['Microsoft.VSTS.TCM.AutomatedTestStorage'])},
    {label: 'Created Date', value: formatDateTime(fields['System.CreatedDate'])},
    {label: 'Created By', value: toIdentityDisplay(fields['System.CreatedBy'])},
    {label: 'Changed Date', value: formatDateTime(fields['System.ChangedDate'])},
    {label: 'Changed By', value: toIdentityDisplay(fields['System.ChangedBy'])},
    {label: 'Activated Date', value: formatDateTime(fields['Microsoft.VSTS.Common.ActivatedDate'])},
    {label: 'Activated By', value: toIdentityDisplay(fields['Microsoft.VSTS.Common.ActivatedBy'])},
    {label: 'Last Updated', value: formatDateTime(testCase.lastUpdatedDate)},
    {label: 'Last Updated By', value: testCase.lastUpdatedBy?.displayName || ''},
  ];
}

export function TestCaseDetail({
  plan,
  suite,
  caseId,
  caseData,
  workspaceSettings,
  onBackToCases,
  onClone,
  onTitleChange,
  onCaseUpdated,
  onHelpClick,
  onSettingsClick,
  embedded = false,
}: TestCaseDetailProps) {
  const [testCase, setTestCase] = useState<ADOTestCase | null>(null);
  const [loading, setLoading] = useState(true);
  const [isDetailLoaded, setIsDetailLoaded] = useState(false);
  const [loadWarning, setLoadWarning] = useState<string | null>(null);
  const [isEditMode, setIsEditMode] = useState(false);
  const [isAdditionalModalOpen, setIsAdditionalModalOpen] = useState(false);
  const [editFormData, setEditFormData] = useState({
    title: '',
    status: '',
    method: '',
    region: '',
    execProcess: '',
    pltpProcess: '',
    initialSteps: '',
  });
  const [editValidationErrors, setEditValidationErrors] = useState<string[]>([]);
  const [editSteps, setEditSteps] = useState<ParsedStep[]>([]);
  const [isSaving, setIsSaving] = useState(false);
  const [showUnsavedConfirm, setShowUnsavedConfirm] = useState(false);
  const [pendingExitAction, setPendingExitAction] = useState<'back' | 'exit' | 'window-close' | null>(null);
  const [confirmExitRequested, setConfirmExitRequested] = useState(false);
  const [stepSearchQuery, setStepSearchQuery] = useState('');
  const [activeStepSearchMatch, setActiveStepSearchMatch] = useState(0);
  const [stepSearchScrollNonce, setStepSearchScrollNonce] = useState(0);
  const editStepsSearch = useStepsSearch();
  const [sharedStepPreviewId, setSharedStepPreviewId] = useState<string | null>(null);
  const [isAutomationManagerOpen, setIsAutomationManagerOpen] = useState(false);
  const [automationRefreshToken, setAutomationRefreshToken] = useState(0);
  const [isAutomationActionBusy, setIsAutomationActionBusy] = useState(false);
  const [showRemoveAutomationConfirm, setShowRemoveAutomationConfirm] = useState(false);
  const [pendingRemoveAssociation, setPendingRemoveAssociation] = useState<{ filePath: string; methodName: string } | null>(null);
  const [isRunModalOpen, setIsRunModalOpen] = useState(false);
  const [isRunBusy, setIsRunBusy] = useState(false);
  const [activeRunId, setActiveRunId] = useState<string | null>(null);
  const [runStatus, setRunStatus] = useState<'idle' | 'running' | 'complete' | 'failed' | 'cancelled'>('idle');
  const [runMode, setRunMode] = useState<TestExecutionMode>('run');
  const [isDebuggerPaused, setIsDebuggerPaused] = useState(false);
  const [debuggerThreadId, setDebuggerThreadId] = useState<number | null>(null);
  const [debuggerStopDetails, setDebuggerStopDetails] = useState<DesktopDebuggerStopDetails | null>(null);
  const [openDetailMenu, setOpenDetailMenu] = useState<DetailMenuType>(null);
  const [runLogEntries, setRunLogEntries] = useState<TestRunLogEntry[]>([]);
  const [runAttachments, setRunAttachments] = useState<string[]>([]);
  const reloadCaseControllerRef = useRef<AbortController | null>(null);
  const runLogViewportRef = useRef<HTMLDivElement | null>(null);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const editBaselineRef = useRef<{
    formData: typeof editFormData;
    steps: ParsedStep[];
  } | null>(null);
  const actionMenusRef = useRef<HTMLDivElement | null>(null);
  const allowWindowCloseRef = useRef(false);
  const viewStepRefs = useRef<Record<string, HTMLElement | null>>({});
  const { addNotification } = useNotification();

  const workspaceReady = Boolean(
    workspaceSettings.organization.trim()
      && workspaceSettings.projectName.trim()
      && workspaceSettings.patToken.trim(),
  );
  const canOpenInAdo = Boolean(
    workspaceSettings.organization.trim()
      && workspaceSettings.projectName.trim(),
  );
  const seleniumRepoPath = workspaceSettings.seleniumRepoPath.trim();

  useEffect(() => {
    let active = true;
    const controller = new AbortController();

    const selectedCase = caseData && caseData.id === caseId ? caseData : null;
    setTestCase((previous) => {
      if (previous && previous.id === caseId) {
        return previous;
      }
      return selectedCase;
    });
    setIsDetailLoaded(false);
    setLoadWarning(null);

    if (!workspaceReady) {
      setLoading(false);
      if (selectedCase) {
        setLoadWarning('Showing test case data from suite list. Configure workspace connection to sync full work item details.');
      } else {
        setLoadWarning('Configure Organization, Project, and PAT in Settings to load work item details.');
      }
      return () => {
        active = false;
      };
    }

    const loadCase = async () => {
      try {
        setLoading(true);
        const preferredHref = selectedCase?._links?.workItem?.href
          ?? selectedCase?._links?.self?.href
          ?? selectedCase?._links?._self?.href;
        const data = await fetchTestCaseDetail(
          workspaceSettings,
          caseId,
          preferredHref,
          selectedCase ?? undefined,
          controller.signal,
        );
        if (!active) return;
        setTestCase((prev) => mergeTestCaseData(data, prev ?? selectedCase));
        setIsDetailLoaded(true);
        setLoadWarning(null);
      } catch (error) {
        if (!active) return;
        const message = error instanceof Error ? error.message : 'Failed to load work item details.';
        setIsDetailLoaded(false);
        if (selectedCase) {
          setLoadWarning(`Showing suite data. Live sync failed: ${message}`);
          return;
        }
        setLoadWarning(message);
      } finally {
        if (active) {
          setLoading(false);
        }
      }
    };

    loadCase().then(() => console.log('[TestCaseDetail] Initial load completed', { caseId, caseDataLoaded: !!caseData, workspaceReady }));
    return () => {
      active = false;
      controller.abort();
    };
  }, [caseData, caseId, workspaceReady, workspaceSettings]);

  useEffect(() => () => {
    reloadCaseControllerRef.current?.abort();
    reloadCaseControllerRef.current = null;
  }, []);

  useEffect(() => {
    if (!isAdditionalModalOpen) return;

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setIsAdditionalModalOpen(false);
      }
    };

    window.addEventListener('keydown', onKeyDown);
    return () => {
      window.removeEventListener('keydown', onKeyDown);
    };
  }, [isAdditionalModalOpen]);

  useEffect(() => {
    if (isEditMode && testCase) {
      const fields = testCase.fields ?? {};
      const newFormData = {
        title: testCase.name || '',
        status: testCase.state || '',
        method: toDisplayValue(fields['Custom.TestingMethod']) || '',
        region: toDisplayValue(fields['Custom.ApplicableRegions']) || '',
        execProcess: toDisplayValue(fields['Custom.ExecutiveProcess']) || '',
        pltpProcess: toDisplayValue(fields['Custom.PLTPProcessArea']) || '',
        initialSteps: normalizeFieldText(fields['Custom.InitialStep']) || '',
      };

      setEditFormData(newFormData);

      // Initialize edit steps from current test case
      const rawSteps = fields['Microsoft.VSTS.TCM.Steps'];
      if (rawSteps) {
        const { steps } = parseXMLSteps(normalizeFieldText(rawSteps).trim());
        const normalizedSteps = steps.map((step, idx) => applyAutoGeneratedDescription({ ...step, index: idx + 1 }));
        setEditSteps(normalizedSteps);
        editBaselineRef.current = {
          formData: newFormData,
          steps: normalizedSteps,
        };
      } else {
        setEditSteps([]);
        editBaselineRef.current = {
          formData: newFormData,
          steps: [],
        };
      }

      setEditValidationErrors([]);
      setShowUnsavedConfirm(false);
      setPendingExitAction(null);
    }
  }, [isEditMode, testCase]);

  const isEditDirty = useMemo(() => {
    const baseline = editBaselineRef.current;
    if (!isEditMode || !baseline) return false;

    const normalizeStep = (step: ParsedStep) => {
      const { index: _index, ...rest } = step as ParsedStep & { index?: number };
      return rest;
    };

    return JSON.stringify(editFormData) !== JSON.stringify(baseline.formData)
      || JSON.stringify(editSteps.map(normalizeStep)) !== JSON.stringify(baseline.steps.map(normalizeStep));
  }, [editFormData, editSteps, isEditMode]);

  useEffect(() => {
    if (!isEditDirty) return;

    const handleBeforeUnload = (event: BeforeUnloadEvent) => {
      if (allowWindowCloseRef.current) {
        return;
      }

      event.preventDefault();
      event.returnValue = '';
    };

    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
    };
  }, [isEditDirty]);

  useEffect(() => {
    window.desktop?.setUnsavedChanges?.(`test-case-edit:${caseId}`, isEditDirty);

    return () => {
      window.desktop?.setUnsavedChanges?.(`test-case-edit:${caseId}`, false);
    };
  }, [caseId, isEditDirty]);

  useEffect(() => {
    if (!isEditDirty) return;

    return window.desktop?.onWindowCloseRequested?.(() => {
      setPendingExitAction('window-close');
      setShowUnsavedConfirm(true);
    });
  }, [isEditDirty]);

  const requestExitEdit = useCallback((action: 'back' | 'exit' | 'window-close') => {
    if (isEditDirty) {
      setPendingExitAction(action);
      setShowUnsavedConfirm(true);
      return;
    }

    if (action === 'back') {
      onBackToCases();
      return;
    }

    setIsEditMode(false);
  }, [isEditDirty, onBackToCases]);

  const discardEditChanges = useCallback(() => {
    setShowUnsavedConfirm(false);
    setConfirmExitRequested(true);
  }, []);

  const keepEditing = useCallback(() => {
    allowWindowCloseRef.current = false;
    if (pendingExitAction === 'window-close') {
      window.desktop?.respondToWindowClose?.(false);
    }
    setPendingExitAction(null);
    setShowUnsavedConfirm(false);
  }, [pendingExitAction]);

  useEffect(() => {
    if (showUnsavedConfirm || !confirmExitRequested || pendingExitAction === null) return;

    const action = pendingExitAction;
    setConfirmExitRequested(false);
    setPendingExitAction(null);
    editBaselineRef.current = null;

    if (action === 'back') {
      setIsEditMode(false);
      onBackToCases();
      return;
    }

    if (action === 'window-close') {
      allowWindowCloseRef.current = true;
      window.desktop?.respondToWindowClose?.(true);
      return;
    }

    setIsEditMode(false);
  }, [confirmExitRequested, onBackToCases, pendingExitAction, showUnsavedConfirm]);

  const handleRefresh = useCallback(async () => {
    if (!testCase || isRefreshing) return;
    if (!workspaceReady) {
      addNotification('error', 'Configure Organization, Project, and PAT in Settings before refreshing.');
      return;
    }
    if (isEditMode && isEditDirty) {
      const proceed = window.confirm(
        'Refreshing will discard unsaved changes in Edit mode. Continue?',
      );
      if (!proceed) return;
    }

    reloadCaseControllerRef.current?.abort();
    const controller = new AbortController();
    reloadCaseControllerRef.current = controller;
    setIsRefreshing(true);
    try {
      const href = testCase._links?.workItem?.href ?? testCase._links?.self?.href;
      const updated = await fetchTestCaseDetail(
        workspaceSettings,
        testCase.id,
        href,
        undefined,
        controller.signal,
      );
      setTestCase(updated);
      setLoadWarning(null);
      addNotification('success', `Refreshed test case #${updated.id}.`);
    } catch (error) {
      if (controller.signal.aborted) return;
      const message = error instanceof Error ? error.message : 'Failed to refresh test case.';
      addNotification('error', message);
    } finally {
      if (reloadCaseControllerRef.current === controller) {
        reloadCaseControllerRef.current = null;
      }
      setIsRefreshing(false);
    }
  }, [addNotification, isEditDirty, isEditMode, isRefreshing, testCase, workspaceReady, workspaceSettings]);

  const reloadCurrentTestCase = useCallback(async (currentCase: ADOTestCase, successMessage?: string) => {
    reloadCaseControllerRef.current?.abort();
    const controller = new AbortController();
    reloadCaseControllerRef.current = controller;

    const href = currentCase._links?.workItem?.href ?? currentCase._links?.self?.href;
    const updatedCase = await fetchTestCaseDetail(
      workspaceSettings,
      currentCase.id,
      href,
      undefined,
      controller.signal,
    );

    setTestCase(updatedCase);
    setIsDetailLoaded(true);
    setLoadWarning(null);
    setAutomationRefreshToken((current) => current + 1);

    if (successMessage) {
      addNotification('success', successMessage);
    }

    if (reloadCaseControllerRef.current === controller) {
      reloadCaseControllerRef.current = null;
    }

    return updatedCase;
  }, [addNotification, workspaceSettings]);

  const syncSingleCaseToLocalDb = useCallback(async (caseToSync: ADOTestCase, options?: { requireAutomated?: boolean }) => {
    if (!window.desktop?.syncDbUpdaterTestCase) {
      throw new Error('Local DB sync is unavailable. Restart the app to load the latest desktop bridge.');
    }
    const result = await window.desktop.syncDbUpdaterTestCase(workspaceSettings, {
      planId: plan.id,
      suiteId: suite.id,
      suiteName: suite.name,
      testCaseId: caseToSync.id,
    });
    if (result.status === 'skipped') {
      throw new Error(result.reason ?? 'Local DB sync skipped for this plan mapping.');
    }
    if (options?.requireAutomated && !result.hasAutomation) {
      throw new Error('DB row synced but automation status is still Manual.');
    }
    return result;
  }, [plan.id, suite.id, suite.name, workspaceSettings]);

  const handleSaveChanges = useCallback(async () => {
    if (!testCase || isSaving) return;

    const errors: string[] = [];
    if (!editFormData.title.trim()) errors.push('Test Title is required');
    if (!editFormData.status.trim()) errors.push('Status is required');
    if (!editFormData.method.trim()) errors.push('Testing Method is required');
    if (!editFormData.region.trim()) errors.push('Region is required');
    if (!editFormData.execProcess.trim()) errors.push('Executive Process is required');
    if (!editFormData.pltpProcess.trim()) errors.push('PLTP Process is required');
    if (editSteps.length === 0) errors.push('At least one step is required');

    editSteps.forEach((step, idx) => {
      if (!step.action.trim()) {
        errors.push(`Step ${idx + 1}: Action is required`);
        return;
      }

      const actionDef = ACTION_REGISTRY[step.action];

      if (actionDef?.contract.locator === 'required' && !step.element?.trim()) {
        errors.push(`Step ${idx + 1}: Locator is required`);
      }

      if (!step.description?.trim()) {
        errors.push(`Step ${idx + 1}: Step Description is required`);
      }
    });

    if (errors.length > 0) {
      setEditValidationErrors(errors);
      return;
    }

    setIsSaving(true);
    let reloadController: AbortController | null = null;
    try {
      const testCaseData = buildTestCaseData(editFormData, editSteps);

      console.log('[TestCaseDetail Save] Steps being saved:', {
        stepCount: editSteps.length,
        xmlLength: testCaseData.stepsXml?.length || 0,
        xmlPreview: testCaseData.stepsXml?.substring(0, 200),
      });

      await updateTestCase(
        workspaceSettings,
        testCase.id,
        testCaseData,
        testCase._links?.workItem?.href ?? testCase._links?.self?.href,
      );

      console.log('[TestCaseDetail] Fetching updated test case after save...');
      reloadCaseControllerRef.current?.abort();
      reloadController = new AbortController();
      reloadCaseControllerRef.current = reloadController;
      const updatedCase = await fetchTestCaseDetail(
        workspaceSettings,
        testCase.id,
        testCase._links?.workItem?.href ?? testCase._links?.self?.href,
        undefined,
        reloadController.signal,
      );
      console.log('[TestCaseDetail] Updated test case received:', {
        id: updatedCase.id,
        stepsCount: (updatedCase.fields?.['Microsoft.VSTS.TCM.Steps'] as string)?.length || 0,
        hasSteps: !!updatedCase.fields?.['Microsoft.VSTS.TCM.Steps'],
      });
      const editedTitle = editFormData.title;
      const updatedTitle = editedTitle || normalizeFieldText(updatedCase.fields?.['System.Title']);
      const nextUpdatedCase = updatedTitle
        ? {
            ...updatedCase,
            name: updatedTitle,
            fields: {
              ...updatedCase.fields,
              'System.Title': updatedTitle,
            },
          }
        : updatedCase;
      setTestCase(nextUpdatedCase);
      onTitleChange?.(nextUpdatedCase.name);
      onCaseUpdated?.(nextUpdatedCase);
      setIsEditMode(false);
      setEditValidationErrors([]);
      editBaselineRef.current = null;
      setShowUnsavedConfirm(false);
      setPendingExitAction(null);
      const updatedAutomatedName = normalizeFieldText(updatedCase?.fields?.['Microsoft.VSTS.TCM.AutomatedTestName']).trim();
      const updatedAutomatedStorage = normalizeFieldText(updatedCase?.fields?.['Microsoft.VSTS.TCM.AutomatedTestStorage']).trim();
      const shouldSyncAfterSave = hasAutomationFieldValue(updatedAutomatedName)
        && hasAutomationFieldValue(updatedAutomatedStorage);
      if (shouldSyncAfterSave) {
        try {
          await syncSingleCaseToLocalDb(updatedCase, { requireAutomated: true });
          addNotification('success', 'Local DB synced for automated test update.');
        } catch (syncError) {
          const syncMessage = syncError instanceof Error ? syncError.message : 'Local DB sync failed.';
          addNotification('error', `Local DB sync failed: ${syncMessage}`);
        }
      }
      addNotification('success', `Test case "${nextUpdatedCase.name}" updated successfully.`);
      if (reloadCaseControllerRef.current === reloadController) {
        reloadCaseControllerRef.current = null;
      }
    } catch (error) {
      if (reloadController?.signal.aborted) {
        return;
      }
      const message = error instanceof Error ? error.message : 'Failed to save changes';
      setEditValidationErrors([`Save failed: ${message}`]);
    } finally {
      if (!reloadController?.signal.aborted) {
        setIsSaving(false);
      }
    }
  }, [addNotification, editFormData, editSteps, isSaving, onCaseUpdated, onTitleChange, syncSingleCaseToLocalDb, testCase, workspaceSettings]);

  const detailHeadingTitle = isEditMode
    ? (editFormData.title || testCase?.name || '')
    : (testCase?.name || '');
  const canClone = Boolean(onClone && testCase && isDetailLoaded && !loading && !isSaving && !isRefreshing && !isEditMode);
  const currentAutomatedTestName = normalizeFieldText(testCase?.fields?.['Microsoft.VSTS.TCM.AutomatedTestName']).trim();
  const currentAutomatedTestStorage = normalizeFieldText(testCase?.fields?.['Microsoft.VSTS.TCM.AutomatedTestStorage']).trim();
  const canOpenAutomationManager = Boolean(
    testCase
      && !loading
      && !isSaving
      && !isRefreshing
      && !isEditMode,
  );
  const automationManagerDisabledReason = 'Open automation manager';

  const automationMethodName = useMemo(() => {
    if (!testCase) return '';
    return buildAutomatedMethodName(testCase.name, testCase.id);
  }, [testCase]);

  const parsedAutomationAssociation = useMemo(() => {
    return parseAutomatedTestFullName(currentAutomatedTestName);
  }, [currentAutomatedTestName]);
  const hasExistingAutomationMetadata = Boolean(
    parsedAutomationAssociation?.methodName
      && hasAutomationFieldValue(currentAutomatedTestName)
      && hasAutomationFieldValue(currentAutomatedTestStorage),
  );
  const associatedAutomationMethodName = parsedAutomationAssociation?.methodName ?? '';
  const generatedAutomationMethodName = stripLegacyTcPrefix(automationMethodName);
  const runMethodName = associatedAutomationMethodName || generatedAutomationMethodName;
  const isAutomatedForRun = hasExistingAutomationMetadata;
  const runDisabledReason = !isAutomatedForRun
    ? 'Run is available only for automated tests.'
    : !workspaceSettings.testRunWorkingDirectory?.trim() || !workspaceSettings.testRunProjectPath?.trim()
      ? 'Configure test runner settings in Workspace Settings.'
      : !runMethodName.trim()
        ? 'Automation method name is missing.'
        : '';
  const canRunTest = Boolean(
    isAutomatedForRun
      && !isEditMode
      && !loading
      && !isSaving
      && !isRefreshing
      && workspaceSettings.testRunWorkingDirectory?.trim()
      && workspaceSettings.testRunProjectPath?.trim()
      && runMethodName.trim(),
  );
  const isDebugRunnerAvailable = DEBUGGER_UI_ENABLED && Boolean(window.desktop?.debugDotnetTest);
  const canDebugTest = DEBUGGER_UI_ENABLED && canRunTest && isDebugRunnerAvailable;
  const debugDisabledReason = !isDebugRunnerAvailable
    ? 'Debug runner is unavailable. Restart the app to load the latest desktop bridge.'
    : runDisabledReason;
  const canReopenRunModal = runLogEntries.length > 0 || isRunBusy;
  const isDebugModeActive = DEBUGGER_UI_ENABLED && runMode === 'debug';
  const displayRunModeLabel: TestExecutionMode = isDebugModeActive ? 'debug' : 'run';
  const hasActiveDebugSession = isDebugModeActive && isRunBusy && Boolean(activeRunId);
  const debuggerScopes = Array.isArray(debuggerStopDetails?.scopes) ? debuggerStopDetails.scopes : [];
  const debuggerCallStack = Array.isArray(debuggerStopDetails?.callStack) ? debuggerStopDetails.callStack : [];
  const debuggerCurrentFrame = debuggerCallStack[0] ?? null;
  const debuggerLocationText = debuggerCurrentFrame
    ? `${debuggerCurrentFrame.sourcePath || debuggerCurrentFrame.sourceName || 'Unknown source'}:${debuggerCurrentFrame.line || 0}`
    : 'Not available';

  const handleClone = useCallback(() => {
    if (!testCase || !onClone) return;

    try {
      const draft = buildCloneDraftFromTestCase(testCase);
      onClone(draft, { id: testCase.id, title: testCase.name });
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to prepare the clone draft.';
      addNotification('error', message);
    }
  }, [addNotification, onClone, testCase]);

  const handleOpenAutomationManager = useCallback(() => {
    if (!canOpenAutomationManager) {
      addNotification('error', automationManagerDisabledReason);
      return;
    }
    if (!seleniumRepoPath) {
      addNotification('error', 'Set Selenium repo path in Settings first.');
      return;
    }
    setIsAutomationManagerOpen(true);
  }, [addNotification, automationManagerDisabledReason, canOpenAutomationManager, seleniumRepoPath]);

  useEffect(() => {
    if (!window.desktop?.onTestRunProgress) {
      return undefined;
    }
    return window.desktop.onTestRunProgress((progress) => {
      if (activeRunId && progress.runId !== activeRunId) return;
      if (!activeRunId) {
        setActiveRunId(progress.runId);
      }
      if (progress.mode === 'run' || progress.mode === 'debug') {
        setRunMode(progress.mode);
      }
      if (progress.debuggerEvent?.event === 'stopped') {
        setIsDebuggerPaused(true);
        setDebuggerThreadId(typeof progress.debuggerEvent.threadId === 'number' ? progress.debuggerEvent.threadId : null);
        setDebuggerStopDetails(progress.debuggerEvent.details ?? null);
      } else if (progress.debuggerEvent?.event === 'continued') {
        setIsDebuggerPaused(false);
        setDebuggerStopDetails(null);
      } else if (progress.debuggerEvent?.event === 'terminated' || progress.debuggerEvent?.event === 'exited') {
        setIsDebuggerPaused(false);
        setDebuggerStopDetails(null);
      }
      if (progress.status !== 'running') {
        setIsDebuggerPaused(false);
        setDebuggerThreadId(null);
        setDebuggerStopDetails(null);
      }
      setRunStatus(progress.status);
      setRunLogEntries((current) => [
        ...current,
        {
          id: `${progress.runId}-${progress.timestamp}-${current.length}`,
          level: progress.level,
          message: progress.message,
          timestamp: progress.timestamp,
        },
      ]);
    });
  }, [activeRunId]);

  useEffect(() => {
    if (!runLogViewportRef.current) return;
    runLogViewportRef.current.scrollTop = runLogViewportRef.current.scrollHeight;
  }, [runLogEntries]);

  useEffect(() => {
    if (!testCase?.id) return;
    if (isRunBusy) return;
    const cached = readCachedLocalExecutionLog(testCase.id);
    if (!cached) return;

    setRunMode(cached.runMode);
    setRunStatus(cached.runStatus);
    setRunLogEntries(
      cached.logEntries.map((entry, index) => ({
        id: `cached-${testCase.id}-${entry.timestamp}-${index}`,
        level: entry.level,
        message: entry.message,
        timestamp: entry.timestamp,
      })),
    );
    setRunAttachments(cached.attachments);
  }, [isRunBusy, testCase?.id]);

  useEffect(() => {
    if (!testCase?.id) return;
    if (runLogEntries.length === 0 && runAttachments.length === 0) return;

    const payload: CachedLocalExecutionLog = {
      runMode,
      runStatus,
      logEntries: runLogEntries.map((entry) => ({
        level: entry.level,
        message: entry.message,
        timestamp: entry.timestamp,
      })),
      attachments: runAttachments,
      savedAt: new Date().toISOString(),
    };
    writeCachedLocalExecutionLog(testCase.id, payload);
  }, [runAttachments, runLogEntries, runMode, runStatus, testCase?.id]);

  useEffect(() => {
    if (!openDetailMenu) return;

    const handleMouseDown = (event: MouseEvent) => {
      if (actionMenusRef.current && !actionMenusRef.current.contains(event.target as Node)) {
        setOpenDetailMenu(null);
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setOpenDetailMenu(null);
      }
    };

    document.addEventListener('mousedown', handleMouseDown);
    window.addEventListener('keydown', handleKeyDown);
    return () => {
      document.removeEventListener('mousedown', handleMouseDown);
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [openDetailMenu]);

  const handleRunCurrentTest = useCallback(async () => {
    if (!window.desktop?.runDotnetTest) {
      addNotification('error', 'Test runner is unavailable. Restart the app to load the latest desktop bridge.');
      return;
    }
    const workingDirectory = workspaceSettings.testRunWorkingDirectory.trim();
    const projectPath = workspaceSettings.testRunProjectPath.trim();
    if (!workingDirectory || !projectPath) {
      addNotification('error', 'Set working directory and project path in Settings > Workspace > Automation Workspace Settings.');
      return;
    }
    if (!runMethodName.trim()) {
      addNotification('error', 'Test method name is unavailable for this test case.');
      return;
    }

    setIsRunModalOpen(true);
    setIsRunBusy(true);
    setRunMode('run');
    setIsDebuggerPaused(false);
    setDebuggerThreadId(null);
    setDebuggerStopDetails(null);
    setActiveRunId(null);
    setRunStatus('running');
    setRunLogEntries([]);
    setRunAttachments([]);

    try {
      const result = await window.desktop.runDotnetTest({
        workingDirectory,
        projectPath,
        runSettingsPath: workspaceSettings.testRunSettingsPath?.trim() || undefined,
        testFilter: `Name=${runMethodName.trim()}`,
        logger: workspaceSettings.testRunLogger?.trim() || 'console;verbosity=detailed',
        patToken: workspaceSettings.patToken,
        passPatAsEnv: workspaceSettings.testRunUsePatAsEnv !== false,
      });
      setActiveRunId(result.runId);
      setRunStatus(result.status);
      setRunAttachments(Array.isArray(result.attachments) ? result.attachments : []);
      if (result.status === 'complete') {
        addNotification('success', `Test run passed for ${runMethodName}.`);
      } else if (result.status === 'cancelled') {
        addNotification('warning', 'Test run cancelled.');
      } else {
        addNotification('error', `Test run failed for ${runMethodName}.`);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to run test.';
      setRunStatus('failed');
      addNotification('error', message);
    } finally {
      setIsRunBusy(false);
    }
  }, [addNotification, runLogEntries, runMethodName, workspaceSettings]);

  const handleDebugCurrentTest = useCallback(async () => {
    if (!window.desktop?.debugDotnetTest) {
      addNotification('error', 'Debug runner is unavailable. Restart the app to load the latest desktop bridge.');
      return;
    }
    const workingDirectory = workspaceSettings.testRunWorkingDirectory.trim();
    const projectPath = workspaceSettings.testRunProjectPath.trim();
    if (!workingDirectory || !projectPath) {
      addNotification('error', 'Set working directory and project path in Settings > Workspace > Automation Workspace Settings.');
      return;
    }
    if (!runMethodName.trim()) {
      addNotification('error', 'Test method name is unavailable for this test case.');
      return;
    }

    setIsRunModalOpen(true);
    setIsRunBusy(true);
    setRunMode('debug');
    setIsDebuggerPaused(false);
    setDebuggerThreadId(null);
    setDebuggerStopDetails(null);
    setActiveRunId(null);
    setRunStatus('running');
    setRunLogEntries([]);
    setRunAttachments([]);

    try {
      const debugBreakpoints = extractDebugBreakpointsFromLogs(runLogEntries);
      const result = await window.desktop.debugDotnetTest({
        workingDirectory,
        projectPath,
        runSettingsPath: workspaceSettings.testRunSettingsPath?.trim() || undefined,
        testFilter: `Name=${runMethodName.trim()}`,
        logger: workspaceSettings.testRunLogger?.trim() || 'console;verbosity=detailed',
        patToken: workspaceSettings.patToken,
        passPatAsEnv: workspaceSettings.testRunUsePatAsEnv !== false,
        breakOnExceptions: true,
        debugBreakpoints: debugBreakpoints.length > 0 ? debugBreakpoints : undefined,
      });
      setActiveRunId(result.runId);
      setRunStatus(result.status);
      setRunAttachments(Array.isArray(result.attachments) ? result.attachments : []);
      if (result.status === 'complete') {
        if (result.debuggerAttached && result.testHostPid) {
          addNotification('success', `Debug run completed (PID ${result.testHostPid} attached).`);
        } else {
          addNotification('warning', 'Debug run completed, but debugger did not attach.');
        }
      } else if (result.status === 'cancelled') {
        addNotification('warning', 'Debug run cancelled.');
      } else {
        addNotification('error', `Debug run failed for ${runMethodName}.`);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to debug test.';
      setRunStatus('failed');
      addNotification('error', message);
    } finally {
      setIsRunBusy(false);
    }
  }, [addNotification, runMethodName, workspaceSettings]);

  const runScreenshotAttachments = useMemo(
    () => runAttachments.filter(isScreenshotAttachment),
    [runAttachments],
  );

  const handleStopRun = useCallback(async () => {
    if (!activeRunId || !window.desktop?.stopDotnetTest) return;
    await window.desktop.stopDotnetTest(activeRunId);
  }, [activeRunId]);

  const handleDebuggerContinue = useCallback(async () => {
    if (!activeRunId || !window.desktop?.debuggerContinue) return;
    await window.desktop.debuggerContinue(activeRunId);
  }, [activeRunId]);

  const handleDebuggerStepOver = useCallback(async () => {
    if (!activeRunId || !window.desktop?.debuggerNext) return;
    await window.desktop.debuggerNext(activeRunId);
  }, [activeRunId]);

  const handleDebuggerStepIn = useCallback(async () => {
    if (!activeRunId || !window.desktop?.debuggerStepIn) return;
    await window.desktop.debuggerStepIn(activeRunId);
  }, [activeRunId]);

  const handleDebuggerStepOut = useCallback(async () => {
    if (!activeRunId || !window.desktop?.debuggerStepOut) return;
    await window.desktop.debuggerStepOut(activeRunId);
  }, [activeRunId]);

  const handleDebuggerPause = useCallback(async () => {
    if (!activeRunId || !window.desktop?.debuggerPause) return;
    await window.desktop.debuggerPause(activeRunId);
  }, [activeRunId]);

  const handleOpenRunArtifact = useCallback(async (targetPath: string) => {
    if (!window.desktop?.openPath) {
      addNotification('error', 'Open file action is unavailable. Restart the app to load the latest desktop bridge.');
      return;
    }
    const result = await window.desktop.openPath(targetPath);
    if (!result?.ok) {
      addNotification('error', result?.error || 'Unable to open selected file.');
    }
  }, [addNotification]);

  const toggleDetailMenu = useCallback((menu: Exclude<DetailMenuType, null>) => {
    setOpenDetailMenu((current) => (current === menu ? null : menu));
  }, []);


  const handleWriteAutomationCode = useCallback(async (filePath: string) => {
    if (!testCase || !generatedAutomationMethodName) {
      return;
    }
    if (!window.desktop?.readTextFile || !window.desktop?.writeTextFile) {
      addNotification('error', 'Desktop file editing is unavailable. Restart the app to load the latest Electron changes.');
      return;
    }

    setIsAutomationActionBusy(true);
    try {
      const fileContent = await window.desktop.readTextFile(filePath);
      ensureMethodDoesNotExist(fileContent, generatedAutomationMethodName);
      const nextFileContent = insertAutomatedTestMethod(
        fileContent,
        buildAutomatedMethodCode(generatedAutomationMethodName),
      );
      await window.desktop.writeTextFile(filePath, nextFileContent);
      setAutomationRefreshToken((current) => current + 1);
      addNotification('success', `Automated test method added to ${getClassNameFromFilePath(filePath)}.`);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to write automated test code.';
      addNotification('error', message);
    } finally {
      setIsAutomationActionBusy(false);
    }
  }, [addNotification, generatedAutomationMethodName, testCase]);

  const handleAddAutomationAssociation = useCallback(async (filePath: string, methodName: string) => {
    if (!testCase) {
      return;
    }
    setIsAutomationActionBusy(true);
    try {
      const className = getClassNameFromFilePath(filePath);
      const fullyQualifiedTestName = buildAutomatedTestFullName(className, methodName);
      const automatedTestId = await createAutomationGuid(fullyQualifiedTestName);
      await updateTestCase(
        workspaceSettings,
        testCase.id,
        {
          automatedTestName: fullyQualifiedTestName,
          automatedTestStorage: currentAutomatedTestStorage || 'BromCom.Tests.dll',
          automatedTestType: 'Unit Test',
          automatedTestId,
          automationStatus: 'Automated',
        },
        testCase._links?.workItem?.href ?? testCase._links?.self?.href,
      );
      const reloaded = await reloadCurrentTestCase(testCase, 'Automated test association added.');
      try {
        const syncResult = await syncSingleCaseToLocalDb(reloaded, { requireAutomated: true });
        addNotification('success', `Local DB synced (${syncResult.dbName ?? 'mapped DB'}).`);
      } catch (syncError) {
        try {
          const retryResult = await syncSingleCaseToLocalDb(reloaded, { requireAutomated: true });
          addNotification('success', `Local DB synced on retry (${retryResult.dbName ?? 'mapped DB'}).`);
        } catch (retryError) {
          const retryMessage = retryError instanceof Error ? retryError.message : 'Local DB sync failed.';
          addNotification('error', `Local DB sync failed after retry: ${retryMessage}`);
        }
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to add automated test association.';
      addNotification('error', message);
    } finally {
      setIsAutomationActionBusy(false);
    }
  }, [addNotification, currentAutomatedTestStorage, reloadCurrentTestCase, syncSingleCaseToLocalDb, testCase, workspaceSettings]);

  const requestRemoveAutomationAssociation = useCallback((filePath: string, methodName: string) => {
    if (!testCase) {
      return;
    }
    if (associatedAutomationMethodName !== methodName) {
      addNotification('error', 'Only the currently associated automated test can be removed.');
      return;
    }
    setPendingRemoveAssociation({ filePath, methodName });
    setShowRemoveAutomationConfirm(true);
  }, [addNotification, associatedAutomationMethodName, testCase]);

  const cancelRemoveAutomationAssociation = useCallback(() => {
    setShowRemoveAutomationConfirm(false);
    setPendingRemoveAssociation(null);
  }, []);

  const handleRemoveAutomationAssociation = useCallback(async () => {
    if (!testCase || !pendingRemoveAssociation) {
      return;
    }
    setIsAutomationActionBusy(true);
    setShowRemoveAutomationConfirm(false);
    try {
      try {
        await updateTestCase(
          workspaceSettings,
          testCase.id,
          {
            automatedTestName: null,
            automatedTestStorage: null,
            automatedTestType: null,
            automatedTestId: null,
            automationStatus: 'Not Automated',
            removeAutomationAssociation: true,
          },
          testCase._links?.workItem?.href ?? testCase._links?.self?.href,
        );
      } catch (error) {
        const message = error instanceof Error ? error.message : '';
        if (!/Automation status/i.test(message)) {
          throw error;
        }
        await updateTestCase(
          workspaceSettings,
          testCase.id,
          {
            automatedTestName: null,
            automatedTestStorage: null,
            automatedTestType: null,
            automatedTestId: null,
            removeAutomationAssociation: true,
          },
          testCase._links?.workItem?.href ?? testCase._links?.self?.href,
        );
      }
      const reloaded = await reloadCurrentTestCase(testCase, 'Automated test association removed.');
      try {
        if (!window.desktop?.deleteDbUpdaterTestCase) {
          throw new Error('Local DB delete is unavailable. Restart the app to load the latest desktop bridge.');
        }
        const deleteResult = await window.desktop.deleteDbUpdaterTestCase(workspaceSettings, {
          planId: plan.id,
          testCaseId: reloaded.id,
        });
        if (deleteResult.status === 'skipped') {
          addNotification('warning', deleteResult.reason ?? 'Local DB delete was skipped.');
        } else {
          addNotification('success', `Removed test from local DB (${deleteResult.deleted ?? 0} row deleted).`);
        }
      } catch (deleteError) {
        const deleteMessage = deleteError instanceof Error ? deleteError.message : 'Local DB delete failed.';
        addNotification('error', deleteMessage);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to remove automated test association.';
      addNotification('error', message);
    } finally {
      setPendingRemoveAssociation(null);
      setIsAutomationActionBusy(false);
    }
  }, [addNotification, pendingRemoveAssociation, plan.id, reloadCurrentTestCase, testCase, workspaceSettings]);

  useEffect(() => {
    if (!isEditMode) return;

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.defaultPrevented || event.repeat) return;
      const isSaveShortcut = (event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 's';
      if (!isSaveShortcut) return;

      event.preventDefault();
      event.stopPropagation();
      void handleSaveChanges();
    };

    window.addEventListener('keydown', onKeyDown);
    return () => {
      window.removeEventListener('keydown', onKeyDown);
    };
  }, [handleSaveChanges, isEditMode]);

  const stepsForDisplay = useMemo(() => {
    if (!testCase) return [];
    return parseStepsForDisplay(testCase.fields['Microsoft.VSTS.TCM.Steps']);
  }, [testCase]);

  const stepViewItems = useMemo(() => {
    if (!testCase) return [];
    const items: Array<{ key: string; index: number; name: string; fullText: string; isInitial?: boolean }> = [];
    const initialStepsText = normalizeFieldText(testCase.fields?.['Custom.InitialStep']).trim();
    if (initialStepsText) {
      items.push({
        key: `${testCase.id}-step-0`,
        index: 0,
        name: 'Initial Steps',
        fullText: initialStepsText,
        isInitial: true,
      });
    }

    stepsForDisplay.forEach((step) => {
      items.push({
        key: `${testCase.id}-step-${step.index}`,
        index: step.index,
        name: step.name,
        fullText: step.fullText,
      });
    });

    return items;
  }, [stepsForDisplay, testCase]);

  const matchingViewStepIndices = useMemo(() => {
    const query = stepSearchQuery.trim().toLowerCase();
    if (!query) return [];
    const exactStepNumber = parseExactStepQuery(stepSearchQuery);
    if (exactStepNumber !== null) {
      return stepViewItems
        .map((step, index) => (step.index === exactStepNumber ? index : -1))
        .filter((index) => index >= 0);
    }

    return stepViewItems
      .map((step, index) => {
        const haystack = `${step.index} ${step.name} ${step.fullText}`.toLowerCase();
        return haystack.includes(query) ? index : -1;
      })
      .filter((index) => index >= 0);
  }, [stepSearchQuery, stepViewItems]);

  const activeMatchedViewStepIndex = matchingViewStepIndices[activeStepSearchMatch] ?? null;

  useEffect(() => {
    setActiveStepSearchMatch(0);
  }, [stepSearchQuery]);

  useEffect(() => {
    if (activeStepSearchMatch > 0 && activeStepSearchMatch >= matchingViewStepIndices.length) {
      setActiveStepSearchMatch(Math.max(0, matchingViewStepIndices.length - 1));
    }
  }, [activeStepSearchMatch, matchingViewStepIndices.length]);

  useEffect(() => {
    if (activeMatchedViewStepIndex === null) return;
    const activeStep = stepViewItems[activeMatchedViewStepIndex];
    if (!activeStep) return;
    viewStepRefs.current[activeStep.key]?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, [activeMatchedViewStepIndex, stepViewItems, stepSearchScrollNonce]);


  const mainRows = useMemo(() => {
    if (!testCase) return [];
    return buildMainDetailRows(testCase);
  }, [testCase]);

  const additionalRows = useMemo(() => {
    if (!testCase) return [];
    return buildAdditionalDetailRows(testCase, plan);
  }, [plan, testCase]);

  const loadingView = (
    <div className="cases-loading-state" aria-live="polite">
      <div className="suite-response-skeleton" aria-hidden="true">
        <span className="skeleton skeleton--line" />
        <span className="skeleton skeleton--line" />
        <span className="skeleton skeleton--line skeleton--line-wide" />
        <span className="skeleton skeleton--line" />
        <span className="skeleton skeleton--line-sm" />
      </div>
    </div>
  );

  if (loading && !testCase) {
    if (embedded) return loadingView;
    return (
      <MainLayout title="Test Case Detail" onHelpClick={onHelpClick} onSettingsClick={onSettingsClick}>
        {loadingView}
      </MainLayout>
    );
  }

  if (!testCase) {
    const emptyView = <p className="text-sm text-secondary">Test case not found.</p>;
    if (embedded) return emptyView;
    return (
      <MainLayout title="Test Case Detail" onHelpClick={onHelpClick} onSettingsClick={onSettingsClick}>
        {emptyView}
      </MainLayout>
    );
  }

  const planBreadcrumbLabel = plan.name.trim() || `Plan ${plan.id}`;
  const parentSuiteName = suite.parent?.name?.trim() ?? '';
  const detailBreadcrumbs = [
    { label: 'Plans', onClick: () => requestExitEdit('back'), isLink: true },
    { label: planBreadcrumbLabel, onClick: () => requestExitEdit('back'), isLink: true },
    ...[parentSuiteName, suite.name]
      .filter((item) => item.trim().length > 0)
      .filter((item, index, arr) => index === 0 || item !== arr[index - 1])
      .map((label) => ({
        label,
        isLink: true,
        onClick: () => requestExitEdit('back'),
      })),
  ];
  const content = (
    <>
      <div className={`case-detail-pane${isEditMode ? ' case-detail-pane--edit' : ''}`}>
        <div className="case-detail-pane__header-fixed">
          {loadWarning && <p className="text-sm text-secondary mb-md">{loadWarning}</p>}

          <div className="case-detail-section__head case-detail-section__head--merged case-detail-section__head--fixed">
                <div className="case-detail-section__title-row">
                  {!isEditMode && stepViewItems.length > 0 && (
                    <div className="help-guide__header-search help-guide__header-search--inline">
                      <div className="help-guide__search-container">
                        <label className="help-guide__search" htmlFor="case-step-search">
                          <IconSearch size={16} aria-hidden="true" />
                          <input
                            id="case-step-search"
                            type="text"
                            value={stepSearchQuery}
                            onChange={(event) => setStepSearchQuery(event.target.value)}
                            onKeyDown={(event) => {
                              if (event.key !== 'Enter') return;
                              if (matchingViewStepIndices.length === 0) return;
                              event.preventDefault();
                              const delta = event.shiftKey ? -1 : 1;
                              setActiveStepSearchMatch((current) =>
                                (current + delta + matchingViewStepIndices.length) % matchingViewStepIndices.length,
                              );
                              setStepSearchScrollNonce((n) => n + 1);
                            }}
                            placeholder="Search steps"
                            aria-label="Search steps"
                            aria-controls="case-detail-step-list"
                          />
                          {stepSearchQuery.length > 0 && (
                            <button
                              type="button"
                              className="help-guide__search-clear"
                              onClick={() => setStepSearchQuery('')}
                              aria-label="Clear search"
                              title="Clear"
                            >
                              ×
                            </button>
                          )}
                        </label>
                      </div>

                      {stepSearchQuery.trim() && (
                        <div className="help-guide__search-controls">
                          <button
                            type="button"
                            className="btn btn--secondary btn--icon-sm"
                            disabled={matchingViewStepIndices.length === 0}
                            onClick={() => {
                              if (matchingViewStepIndices.length === 0) return;
                              setActiveStepSearchMatch((current) =>
                                (current - 1 + matchingViewStepIndices.length) % matchingViewStepIndices.length,
                              );
                              setStepSearchScrollNonce((n) => n + 1);
                            }}
                            title={matchingViewStepIndices.length === 0 ? 'No search matches found' : 'Previous match (Shift+Enter)'}
                            aria-label="Previous match"
                          >
                            ↑
                          </button>
                          <button
                            type="button"
                            className="btn btn--secondary btn--icon-sm"
                            disabled={matchingViewStepIndices.length === 0}
                            onClick={() => {
                              if (matchingViewStepIndices.length === 0) return;
                              setActiveStepSearchMatch((current) => (current + 1) % matchingViewStepIndices.length);
                              setStepSearchScrollNonce((n) => n + 1);
                            }}
                            title={matchingViewStepIndices.length === 0 ? 'No search matches found' : 'Next match (Enter)'}
                            aria-label="Next match"
                          >
                            ↓
                          </button>
                          <span className="help-guide__match-info" aria-live="polite">
                            {matchingViewStepIndices.length === 0
                              ? '0 / 0'
                              : `${activeStepSearchMatch + 1} / ${matchingViewStepIndices.length}`}
                          </span>
                        </div>
                      )}
                    </div>
                  )}
                  {isEditMode && (
                    <StepsSearchBar
                      controller={editStepsSearch}
                      matchingCount={editStepsSearch.matchingCount}
                      activeIndex={editStepsSearch.activeIndex}
                      onActiveIndexChange={editStepsSearch.setActiveIndex}
                      inputId="edit-step-search"
                    />
                  )}
                </div>
                <div className="case-detail-section__actions" ref={actionMenusRef}>
                  {!isEditMode && (
                    <div className="case-detail-toolbar-menus">
                      <button
                        type="button"
                        className="btn btn--secondary btn--sm case-detail-action-btn"
                        onClick={() => { void handleRefresh(); }}
                        aria-label="Refresh"
                        title={!workspaceReady ? 'Configure Organization, Project, and PAT in Settings first' : isRefreshing ? 'Refreshing...' : 'Refresh from Azure DevOps'}
                        disabled={isRefreshing || !workspaceReady}
                      >
                        <span
                          className="material-symbols"
                          aria-hidden="true"
                          style={isRefreshing ? { animation: 'spin 1s linear infinite' } : undefined}
                        >
                          refresh
                        </span>
                        <span>Refresh</span>
                      </button>

                      <div className={`case-detail-toolbar-menu${openDetailMenu === 'more-details' ? ' is-open' : ''}`}>
                        <button
                          type="button"
                          className="btn btn--secondary btn--sm case-detail-action-btn"
                          aria-haspopup="menu"
                          aria-expanded={openDetailMenu === 'more-details'}
                          onClick={() => toggleDetailMenu('more-details')}
                        >
                          <span className="material-symbols" aria-hidden="true">info</span>
                          <span>More info</span>
                          <span className="material-symbols" aria-hidden="true">expand_more</span>
                        </button>
                        {openDetailMenu === 'more-details' && (
                          <div className="action-menu" role="menu">
                            <button
                              type="button"
                              role="menuitem"
                              className="action-menu__item"
                              onClick={() => {
                                setOpenDetailMenu(null);
                                window.open(buildWorkItemAdoUrl(workspaceSettings, testCase.id), '_blank', 'noopener,noreferrer');
                              }}
                              disabled={!canOpenInAdo}
                            >
                              <img className="case-detail__azure-icon" src={azureLogo} alt="" width={16} height={16} aria-hidden="true" />
                              <span>Open in Azure DevOps</span>
                            </button>
                            <button
                              type="button"
                              role="menuitem"
                              className="action-menu__item"
                              onClick={() => {
                                setOpenDetailMenu(null);
                                setIsAdditionalModalOpen(true);
                              }}
                              disabled={additionalRows.length === 0}
                            >
                              <span className="material-symbols" aria-hidden="true">info</span>
                              <span>Additional details</span>
                            </button>
                          </div>
                        )}
                      </div>

                      <div className={`case-detail-toolbar-menu${openDetailMenu === 'action' ? ' is-open' : ''}`}>
                        <button
                          type="button"
                          className="btn btn--secondary btn--sm case-detail-action-btn"
                          aria-haspopup="menu"
                          aria-expanded={openDetailMenu === 'action'}
                          onClick={() => toggleDetailMenu('action')}
                        >
                          <span className="material-symbols" aria-hidden="true">edit</span>
                          <span>Modify</span>
                          <span className="material-symbols" aria-hidden="true">expand_more</span>
                        </button>
                        {openDetailMenu === 'action' && (
                          <div className="action-menu" role="menu">
                            <button
                              type="button"
                              role="menuitem"
                              className="action-menu__item"
                              onClick={() => {
                                setOpenDetailMenu(null);
                                setIsEditMode((prev) => !prev);
                              }}
                            >
                              <span className="material-symbols" aria-hidden="true">edit</span>
                              <span>Edit</span>
                            </button>
                            <button
                              type="button"
                              role="menuitem"
                              className="action-menu__item"
                              onClick={() => {
                                setOpenDetailMenu(null);
                                handleClone();
                              }}
                              disabled={!canClone}
                            >
                              <IconCopy size={16} />
                              <span>Clone / Copy</span>
                            </button>
                          </div>
                        )}
                      </div>

                      <button
                        type="button"
                        className="btn btn--secondary btn--sm case-detail-action-btn"
                        onClick={() => { void handleOpenAutomationManager(); }}
                        aria-label="Open automation manager"
                        title={canOpenAutomationManager ? automationManagerDisabledReason : 'Automation manager is unavailable while loading, saving, refreshing, or editing'}
                        disabled={!canOpenAutomationManager}
                      >
                        <IconFolderCode size={16} />
                        <span>Automation Manager</span>
                      </button>

                      <div className={`case-detail-toolbar-menu${openDetailMenu === 'local-execution' ? ' is-open' : ''}`}>
                        <button
                          type="button"
                          className="btn btn--secondary btn--sm case-detail-action-btn"
                          aria-haspopup="menu"
                          aria-expanded={openDetailMenu === 'local-execution'}
                          onClick={() => toggleDetailMenu('local-execution')}
                        >
                          <span className="material-symbols" aria-hidden="true">terminal</span>
                          <span>Local Execution</span>
                          <span className="material-symbols" aria-hidden="true">expand_more</span>
                        </button>
                        {openDetailMenu === 'local-execution' && (
                          <div className="action-menu" role="menu">
                            <button
                              type="button"
                              role="menuitem"
                              className="action-menu__item"
                              onClick={() => {
                                setOpenDetailMenu(null);
                                void handleRunCurrentTest();
                              }}
                              disabled={!canRunTest || isRunBusy}
                            >
                              <span className="material-symbols" aria-hidden="true">play_arrow</span>
                              <span>Run Locally</span>
                            </button>
                            {DEBUGGER_UI_ENABLED && (
                              <button
                                type="button"
                                role="menuitem"
                                className="action-menu__item"
                                onClick={() => {
                                  setOpenDetailMenu(null);
                                  void handleDebugCurrentTest();
                                }}
                                title={canDebugTest ? `Debug ${runMethodName}` : debugDisabledReason}
                                disabled={!canDebugTest || isRunBusy}
                              >
                                <span className="material-symbols" aria-hidden="true">bug_report</span>
                                <span>Debug Locally</span>
                              </button>
                            )}
                            <button
                              type="button"
                              role="menuitem"
                              className="action-menu__item"
                              onClick={() => {
                                setOpenDetailMenu(null);
                                setIsRunModalOpen(true);
                              }}
                              disabled={!canReopenRunModal}
                            >
                              <span className="material-symbols" aria-hidden="true">receipt_long</span>
                              <span>Local Execution Log</span>
                            </button>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
              {isEditMode && (
                <>
                  <button
                    type="button"
                    className="btn btn--secondary btn--sm"
                    onClick={() => { void handleRefresh(); }}
                    aria-label="Refresh"
                    title={!workspaceReady ? 'Configure Organization, Project, and PAT in Settings first' : isSaving ? 'Save in progress' : isRefreshing ? 'Refreshing...' : 'Refresh from Azure DevOps (discards unsaved changes)'}
                    disabled={isRefreshing || isSaving || !workspaceReady}
                  >
                    <span
                      className="material-symbols"
                      aria-hidden="true"
                      style={isRefreshing ? { animation: 'spin 1s linear infinite' } : undefined}
                    >
                      refresh
                    </span>
                  </button>
                  <button
                    type="button"
                    className="btn btn--primary btn--sm"
                    disabled={isSaving}
                    onClick={() => { void handleSaveChanges(); }}
                    title={isSaving ? 'Saving changes...' : 'Save changes'}
                  >
                    {isSaving ? 'Saving...' : 'Save'}
                  </button>
                  <button
                    type="button"
                    className="btn btn--secondary btn--sm"
                    onClick={() => requestExitEdit('exit')}
                  >
                    Exit Edit
                  </button>
                </>
              )}
            </div>
          </div>
        </div>

        <div className="case-detail-pane__content">
          {!isEditMode ? (
            <>
              {mainRows.length > 0 && (
                <div className="case-detail-grid">
                  {mainRows.map((row) => (
                    <article key={row.label} className="case-detail-card">
                      <span className="case-detail-card__label">{row.label}</span>
                      <p className="case-detail-card__value">{row.value || 'Not set'}</p>
                    </article>
                  ))}
                </div>
              )}

              <div className="case-detail-steps-container">
                {stepViewItems.length > 0 ? (
                  <div id="case-detail-step-list" className="case-detail-steps-list pt-md">
                    {stepViewItems.map((step, stepArrayIndex) => (
                      <article
                        key={step.key}
                        ref={(element) => {
                          viewStepRefs.current[step.key] = element;
                        }}
                        className={`case-detail-step-item${activeMatchedViewStepIndex === stepArrayIndex ? ' is-selected' : ''}`}
                      >
                        <p className="case-detail-step-item__title">
                          <span className="case-detail-step-item__index">Step {step.index}:</span>
                          <strong className="case-detail-step-item__name">{step.name}</strong>
                        </p>
                        <pre className="case-detail-step-item__full">
                          {step.isInitial ? step.fullText : formatStepTextWithBoldLabels(step.fullText)}
                        </pre>
                      </article>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-secondary">No step definition available.</p>
                )}
              </div>
            </>
          ) : (
            <section className="case-detail-edit-section">
              <TestCaseFormFields
                formData={editFormData}
                onChange={(updatedData) => {
                  setEditFormData((prev) => ({ ...prev, ...updatedData }));
                  if (Object.prototype.hasOwnProperty.call(updatedData, 'title')) {
                    onTitleChange?.(updatedData.title ?? '');
                  }
                }}
                isLoading={isSaving}
                showTitle
                validationErrors={editValidationErrors}
                titlePlaceholder="Enter test title"
              />

              <StepsEditor
                rawSteps={testCase.fields['Microsoft.VSTS.TCM.Steps']}
                onChange={setEditSteps}
                errors={editValidationErrors.filter((e) => e.toLowerCase().includes('step'))}
                hideHeader
                externalSearch={editStepsSearch}
                onPreviewSharedStep={setSharedStepPreviewId}
              />

            </section>
          )}
        </div>
      </div>

      {sharedStepPreviewId !== null && (
        <SharedStepPreviewModal
          testId={sharedStepPreviewId}
          workspaceSettings={workspaceSettings}
          onClose={() => setSharedStepPreviewId(null)}
        />
      )}

      {isAutomationManagerOpen && testCase && (
        <SeleniumRepoBrowserModal
          repoPath={seleniumRepoPath}
          mode="manage-automation"
          generatedMethodName={generatedAutomationMethodName}
          associatedMethodName={associatedAutomationMethodName || null}
          associatedClassName={parsedAutomationAssociation?.className ?? null}
          onWriteCode={(filePath) => { void handleWriteAutomationCode(filePath); }}
          onAddAssociation={(filePath, methodName) => { void handleAddAutomationAssociation(filePath, methodName); }}
          onRemoveAssociation={requestRemoveAutomationAssociation}
          actionBusy={isAutomationActionBusy}
          refreshToken={automationRefreshToken}
          onClose={() => {
            if (isAutomationActionBusy) return;
            setIsAutomationManagerOpen(false);
          }}
        />
      )}

      {isAdditionalModalOpen && (
        <div className="settings-overlay" role="dialog" aria-modal="true" aria-label="Additional Details">
          <button
            type="button"
            className="settings-overlay__backdrop"
            onClick={() => setIsAdditionalModalOpen(false)}
            aria-label="Close additional details"
          />
          <div className="settings-dock settings-dock--no-aside">
            <section className="settings-workbench">
              <header className="settings-workbench__header">
                <div>
                  <p className="settings-workbench__crumb">Additional Details</p>
                  <h1 className="settings-workbench__title" title={testCase.name}>{testCase.name}</h1>
                  <p className="settings-workbench__subtitle">Additional information and metadata for this test case.</p>
                </div>
                <button
                  type="button"
                  className="settings-workbench__close"
                  onClick={() => setIsAdditionalModalOpen(false)}
                  aria-label="Close additional details"
                  title="Close additional details"
                >
                  <IconX size={18} />
                </button>
              </header>

              <div className="settings-workbench__body">
                <div className="settings-content">
                  {additionalRows.length > 0 ? (
                    <section className="settings-pane">
                      <div className="case-detail-modal__meta-grid">
                        {additionalRows.map((row) => (
                          <article key={row.label} className="case-detail-modal__meta-card">
                            <span className="case-detail-modal__meta-label">{row.label}</span>
                            <strong className="case-detail-modal__meta-value">{row.value || 'Not set'}</strong>
                          </article>
                        ))}
                      </div>
                    </section>
                  ) : (
                    <p className="text-sm text-secondary">No additional details available.</p>
                  )}
                </div>
              </div>
            </section>
          </div>
        </div>
      )}

      {showUnsavedConfirm && (
        <div className="steps-editor__confirm-overlay" role="dialog" aria-modal="true" aria-label="Unsaved edit changes">
          <button
            type="button"
            className="steps-editor__confirm-backdrop"
            onClick={keepEditing}
            aria-label="Close unsaved changes confirmation"
          />
          <div className="steps-editor__confirm-card steps-editor__confirm-card--warning" role="document">
            <div className="steps-editor__confirm-head">
              <div>
                <p className="steps-editor__confirm-kicker steps-editor__confirm-kicker--warning">Unsaved changes</p>
                <h3 className="steps-editor__confirm-title steps-editor__confirm-title--warning">
                  Discard edits on this test case?
                </h3>
              </div>
              <button
                type="button"
                className="steps-editor__confirm-close"
                onClick={keepEditing}
                aria-label="Close unsaved changes confirmation"
                title="Close"
              >
                <IconX size={16} />
              </button>
            </div>

            <p className="steps-editor__confirm-copy">
              {pendingExitAction === 'window-close'
                ? 'You have unsaved changes in edit mode. Closing the app now will discard your updates to the title, fields, and steps.'
                : 'You have unsaved changes in edit mode. Discarding now will remove your updates to the title, fields, and steps.'}
            </p>

            <div className="steps-editor__confirm-actions">
              <button type="button" className="btn btn--secondary btn--sm" onClick={keepEditing}>
                Keep editing
              </button>
              <button type="button" className="btn btn--danger btn--sm" onClick={discardEditChanges}>
                {pendingExitAction === 'window-close' ? 'Close without saving' : 'Discard changes'}
              </button>
            </div>
          </div>
        </div>
      )}

      {showRemoveAutomationConfirm && (
        <div className="steps-editor__confirm-overlay" role="dialog" aria-modal="true" aria-label="Remove automation association">
          <button
            type="button"
            className="steps-editor__confirm-backdrop"
            onClick={cancelRemoveAutomationAssociation}
            aria-label="Close remove automation association confirmation"
          />
          <div className="steps-editor__confirm-card steps-editor__confirm-card--warning" role="document">
            <div className="steps-editor__confirm-head">
              <div>
                <p className="steps-editor__confirm-kicker steps-editor__confirm-kicker--warning">Remove association</p>
                <h3 className="steps-editor__confirm-title steps-editor__confirm-title--warning">
                  Remove automation association?
                </h3>
              </div>
              <button
                type="button"
                className="steps-editor__confirm-close"
                onClick={cancelRemoveAutomationAssociation}
                aria-label="Close remove automation association confirmation"
                title="Close"
              >
                <IconX size={16} />
              </button>
            </div>

            <p className="steps-editor__confirm-copy">
              This will remove the Azure association and delete this test from the mapped local DB.
            </p>

            <div className="steps-editor__confirm-actions">
              <button type="button" className="btn btn--secondary btn--sm" onClick={cancelRemoveAutomationAssociation}>
                Cancel
              </button>
              <button
                type="button"
                className="btn btn--danger btn--sm"
                onClick={() => { void handleRemoveAutomationAssociation(); }}
                disabled={isAutomationActionBusy}
                title={isAutomationActionBusy ? 'Removing association...' : 'Remove automation association'}
              >
                Remove association
              </button>
            </div>
          </div>
        </div>
      )}

      {isRunModalOpen && (
        <div className="settings-overlay" role="dialog" aria-modal="true" aria-label="Run test progress">
          <button type="button" className="settings-overlay__backdrop" onClick={isRunBusy ? undefined : () => setIsRunModalOpen(false)} />
          <div className="settings-dock settings-dock--no-aside">
            <section className="settings-workbench">
              <header className="settings-workbench__header">
                <div>
                  <p className="settings-workbench__crumb">Test Runner</p>
                  <h1 className="settings-workbench__title">{isDebugModeActive ? 'Debug Progress' : 'Run Progress'}</h1>
                  <p className="settings-workbench__subtitle">
                    {runMethodName} · {displayRunModeLabel} · {runStatus}
                    {isDebugModeActive ? ` · ${isDebuggerPaused ? 'paused' : 'running'}${debuggerThreadId ? ` · thread ${debuggerThreadId}` : ''}` : ''}
                  </p>
                </div>
                <button
                  type="button"
                  className="settings-workbench__close"
                  onClick={() => setIsRunModalOpen(false)}
                  disabled={isRunBusy}
                  title={isRunBusy ? 'Stop run before closing' : 'Close'}
                >
                  <IconX size={18} />
                </button>
              </header>
              <div className="settings-workbench__body">
                <div className="settings-content">
                  <section className="settings-panel db-updater__log-panel">
                    <div className="settings-panel__head db-updater__log-head test-run__log-head">
                      <div>
                        <div className="settings-panel__title">Console log</div>
                      </div>
                      <div className={`db-updater__log-state db-updater__log-state--${runStatus === 'running' ? 'running' : runStatus === 'complete' ? 'complete' : 'error'}`}>
                        <span />
                        {runStatus}
                      </div>
                    </div>
                    <div className="db-updater__log-shell">
                      <div className="test-run__console" ref={runLogViewportRef}>
                        {runLogEntries.length === 0 ? (
                          <div className="db-updater__log-empty"><strong>Waiting for output</strong></div>
                        ) : runLogEntries.map((entry) => (
                          <div className={`test-run__console-line test-run__console-line--${entry.level}`} key={entry.id}>
                            <span className="test-run__console-msg">{entry.message}</span>
                          </div>
                        ))}
                        {runScreenshotAttachments.length > 0 && (
                          <div className="test-run__console-attachments">
                            {runScreenshotAttachments.map((attachmentPath) => {
                              const fileName = attachmentPath.split(/[\\/]/).pop() || attachmentPath;
                              return (
                                <button
                                  key={attachmentPath}
                                  type="button"
                                  className="test-run__console-attachment"
                                  onClick={() => { void handleOpenRunArtifact(attachmentPath); }}
                                  aria-label={`Open attachment ${fileName}`}
                                  title={attachmentPath}
                                >
                                  <IconAttachFile size={15} />
                                  <span>{fileName}</span>
                                  <IconOpenInNew size={13} />
                                </button>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="test-run__footer">
                      {isRunBusy && isDebugModeActive ? (
                        <>
                          <button
                            type="button"
                            className="btn btn--secondary btn--sm"
                            onClick={() => { void handleDebuggerContinue(); }}
                            disabled={!hasActiveDebugSession || !isDebuggerPaused}
                            title={isDebuggerPaused ? 'Continue execution' : 'Debugger is not paused'}
                          >
                            Continue
                          </button>
                          <button
                            type="button"
                            className="btn btn--secondary btn--sm"
                            onClick={() => { void handleDebuggerStepOver(); }}
                            disabled={!hasActiveDebugSession || !isDebuggerPaused}
                            title={isDebuggerPaused ? 'Step over (next)' : 'Debugger is not paused'}
                          >
                            Step Over
                          </button>
                          <button
                            type="button"
                            className="btn btn--secondary btn--sm"
                            onClick={() => { void handleDebuggerStepIn(); }}
                            disabled={!hasActiveDebugSession || !isDebuggerPaused}
                            title={isDebuggerPaused ? 'Step into' : 'Debugger is not paused'}
                          >
                            Step Into
                          </button>
                          <button
                            type="button"
                            className="btn btn--secondary btn--sm"
                            onClick={() => { void handleDebuggerStepOut(); }}
                            disabled={!hasActiveDebugSession || !isDebuggerPaused}
                            title={isDebuggerPaused ? 'Step out' : 'Debugger is not paused'}
                          >
                            Step Out
                          </button>
                          <button
                            type="button"
                            className="btn btn--secondary btn--sm"
                            onClick={() => { void handleDebuggerPause(); }}
                            disabled={!hasActiveDebugSession || isDebuggerPaused}
                            title={isDebuggerPaused ? 'Debugger is already paused' : 'Pause execution'}
                          >
                            Pause
                          </button>
                          <button type="button" className="btn btn--danger btn--sm" onClick={() => { void handleStopRun(); }}>
                            Stop run
                          </button>
                        </>
                      ) : null}
                      {isRunBusy && !isDebugModeActive ? (
                        <button type="button" className="btn btn--danger btn--sm" onClick={() => { void handleStopRun(); }}>
                          Stop run
                        </button>
                      ) : null}
                    </div>
                  </section>
                  {isDebugModeActive && (
                    <section className="settings-panel db-updater__log-panel test-run__debug-panel">
                      <div className="settings-panel__head db-updater__log-head test-run__log-head">
                        <div>
                          <div className="settings-panel__title">Paused context</div>
                        </div>
                        <div className={`db-updater__log-state db-updater__log-state--${isDebuggerPaused ? 'running' : 'error'}`}>
                          <span />
                          {isDebuggerPaused ? 'paused' : 'waiting'}
                        </div>
                      </div>
                      <div className="db-updater__log-shell test-run__debug-shell">
                        {!isDebuggerPaused ? (
                          <div className="db-updater__log-empty"><strong>Debugger is running</strong></div>
                        ) : (
                          <div className="test-run__debug-content">
                            <div className="test-run__debug-summary">
                              <div><strong>Location:</strong> {debuggerLocationText}</div>
                              <div><strong>Reason:</strong> {debuggerStopDetails?.reason || 'breakpoint'}</div>
                              {debuggerStopDetails?.description ? (
                                <div><strong>Exception:</strong> {debuggerStopDetails.description}</div>
                              ) : null}
                            </div>

                            <div className="test-run__debug-block">
                              <h3>Call stack</h3>
                              {debuggerCallStack.length === 0 ? (
                                <div className="db-updater__log-empty"><strong>No frames available</strong></div>
                              ) : (
                                <div className="test-run__debug-list">
                                  {debuggerCallStack.map((frame) => {
                                    const frameKey = `${frame.id}-${frame.name}-${frame.line}-${frame.column}`;
                                    const frameLocation = `${frame.sourcePath || frame.sourceName || 'Unknown source'}:${frame.line || 0}`;
                                    return (
                                      <div key={frameKey} className="test-run__debug-row">
                                        <div className="test-run__debug-row-title">{frame.name || '(anonymous)'}</div>
                                        <div className="test-run__debug-row-meta">{frameLocation}</div>
                                      </div>
                                    );
                                  })}
                                </div>
                              )}
                            </div>

                            <div className="test-run__debug-block">
                              <h3>Variables</h3>
                              {debuggerScopes.length === 0 ? (
                                <div className="db-updater__log-empty"><strong>No scopes available</strong></div>
                              ) : (
                                <div className="test-run__debug-scopes">
                                  {debuggerScopes.map((scope) => (
                                    <div key={scope.name} className="test-run__debug-scope">
                                      <div className="test-run__debug-scope-title">{scope.name}</div>
                                      {scope.variables.length === 0 ? (
                                        <div className="test-run__debug-row-meta">No variables</div>
                                      ) : (
                                        <div className="test-run__debug-list">
                                          {scope.variables.map((variable) => (
                                            <div key={`${scope.name}-${variable.name}`} className="test-run__debug-row">
                                              <div className="test-run__debug-var-name">{variable.name}</div>
                                              <div className="test-run__debug-var-value">{variable.value}</div>
                                            </div>
                                          ))}
                                        </div>
                                      )}
                                    </div>
                                  ))}
                                </div>
                              )}
                            </div>
                          </div>
                        )}
                      </div>
                    </section>
                  )}
                </div>
              </div>
            </section>
          </div>
        </div>
      )}

    </>
  );

  if (embedded) return content;

  return (
    <MainLayout title="Test Case Detail" onHelpClick={onHelpClick} onSettingsClick={onSettingsClick}>
      <PageDetailLayout
        breadcrumbs={detailBreadcrumbs}
        heading={{
          title: detailHeadingTitle,
          id: testCase.id,
          count: stepsForDisplay.length,
          countLabel: 'Steps',
        }}
      >
        {content}
      </PageDetailLayout>
    </MainLayout>
  );
}


