import type { ADOTestCase } from '../types';
import type { ParsedStep } from '../components/TestCases/StepsEditor';
import { parseXMLSteps } from './xmlParser';
import { applyAutoGeneratedDescription } from './stepSmartDefaults';

export interface CreateTestCaseDraftFormData {
  title: string;
  status: string;
  method: string;
  region: string;
  execProcess: string;
  pltpProcess: string;
  initialSteps: string;
}

export interface CreateTestCaseDraft {
  formData: CreateTestCaseDraftFormData;
  steps: ParsedStep[];
  validationErrors: string[];
}

export interface CloneSourceMeta {
  id: number;
  title: string;
}

function normalizeFieldText(value: unknown): string {
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return '';
}

function buildClonedTitle(title: string): string {
  const trimmedTitle = title.trim() || 'Untitled Test Case';
  return `${trimmedTitle} - Copy`;
}

export function buildCloneDraftFromTestCase(testCase: ADOTestCase): CreateTestCaseDraft {
  const fields = testCase.fields ?? {};
  const rawSteps = normalizeFieldText(fields['Microsoft.VSTS.TCM.Steps']).trim();
  const parsedResult = rawSteps ? parseXMLSteps(rawSteps) : { steps: [], errors: [], warnings: [] };
  const parsedSteps = parsedResult.steps.map((step, index) => applyAutoGeneratedDescription({ ...step, index: index + 1 }));

  if (rawSteps && parsedSteps.length === 0) {
    throw new Error('The source test case steps could not be converted into a new test draft.');
  }

  return {
    formData: {
      title: buildClonedTitle(testCase.name),
      status: normalizeFieldText(testCase.state).trim(),
      method: normalizeFieldText(fields['Custom.TestingMethod']).trim(),
      region: normalizeFieldText(fields['Custom.ApplicableRegions']).trim(),
      execProcess: normalizeFieldText(fields['Custom.ExecutiveProcess']).trim(),
      pltpProcess: normalizeFieldText(fields['Custom.PLTPProcessArea']).trim(),
      initialSteps: normalizeFieldText(fields['Custom.InitialStep']).trim(),
    },
    steps: parsedSteps,
    validationErrors: [],
  };
}
